# Generated by Django 6.0.3 on 2026-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0002_product_is_bestseller_product_is_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
