# Generated by Django 6.0.3 on 2026-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0003_productimage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_alert',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
