# Generated by Django 6.0.3 on 2026-05-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0004_product_min_stock_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('home', 'À domicile'), ('desk', 'Bureau / Point relais')], default='home', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya_name', models.CharField(max_length=100)),
                ('price_home', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('price_desk', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pioveapp.deliverycompany')),
            ],
            options={
                'ordering': ['wilaya_name'],
                'unique_together': {('company', 'wilaya_name')},
            },
        ),
    ]
