# Generated by Django 6.0.3 on 2026-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0006_customer_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
