# Generated by Django 6.0.3 on 2026-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0007_alter_productvariant_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero Slider (Accueil)'), ('popup', "Pop-up d'entrée"), ('home_section_1', 'Bandeau Section 1 (Accueil)'), ('home_section_2', 'Bandeau Section 2 (Accueil)')], default='hero', max_length=50),
        ),
    ]
