# Generated by Django 6.0.3 on 2026-05-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0008_banner_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero Slider (Accueil)'), ('popup', "Pop-up d'entrée"), ('home_section_1', 'Bandeau Section 1 (Accueil)'), ('home_section_2', 'Bandeau Section 2 (Accueil)'), ('top_banner', 'Bandeau Supérieur (Global)')], default='hero', max_length=50),
        ),
    ]
