# Generated by Django 6.0.3 on 2026-05-29 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0010_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('fulfilled', 'Fulfilled'), ('shipped', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pioveapp.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
