# Generated by Django 6.0.3 on 2026-05-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0011_orderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('shipped', 'En livraison'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('shipped', 'En livraison'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Annulée')], max_length=20),
        ),
    ]
