# Generated by Django 6.0.3 on 2026-05-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0012_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero Slider (Accueil)'), ('popup', "Pop-up d'entrée"), ('home_section_1', 'Bandeau Section 1 (Accueil)'), ('home_section_2', 'Bandeau Section 2 (Accueil)'), ('top_banner', 'Bandeau Supérieur (Global)'), ('category_banner', 'Bandeau Page Catégorie')], default='hero', max_length=50),
        ),
    ]
