# Generated by Django 6.0.3 on 2026-05-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0014_banner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b2b_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_carton',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
    ]
