# Generated by Django 6.0.3 on 2026-05-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0015_product_b2b_price_product_units_per_carton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
    ]
