# Generated by Django 6.0.3 on 2026-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0016_customer_is_b2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Paiement à la livraison'), ('cib', 'CIB ou Edahabia')], default='cash', max_length=20),
        ),
    ]
