# Generated by Django 6.0.3 on 2026-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0017_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('paid', 'Payé'), ('refunded', 'Remboursé')], default='unpaid', max_length=20),
        ),
    ]
