# Generated by Django 6.0.3 on 2026-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0020_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
