# Generated by Django 6.0.3 on 2026-05-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0021_order_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
