# Generated by Django 6.0.3 on 2026-05-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0022_useractivitylog_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_b2b_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nif',
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro d'Identification Fiscale"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nrc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registre de Commerce'),
        ),
    ]
