# Generated by Django 6.0.3 on 2026-05-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0024_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nrc_file',
            field=models.FileField(blank=True, null=True, upload_to='b2b_docs/', verbose_name='Document NRC'),
        ),
    ]
