# Generated by Django 6.0.3 on 2026-05-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0025_userprofile_nrc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('shipped', 'En livraison'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Annulée'), ('returned', 'Retournée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('shipped', 'En livraison'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Annulée'), ('returned', 'Retournée')], max_length=20),
        ),
    ]
