# Generated by Django 6.0.3 on 2026-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0029_product_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b2b_min_stock',
            field=models.PositiveIntegerField(default=1, help_text='Quantité minimale de commande (MOQ) pour B2B'),
        ),
        migrations.AddField(
            model_name='product',
            name='b2b_price_box',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='b2b_price_carton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='b2b_promo_price_box',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='b2b_promo_price_carton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
