# Generated by Django 6.0.3 on 2026-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0030_product_b2b_min_stock_product_b2b_price_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrate',
            name='b2b_price_desk',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryrate',
            name='b2b_price_home',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_box',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Poids par boîte (kg)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_carton',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Poids par carton (kg)', max_digits=6),
        ),
    ]
