# Generated by Django 6.0.3 on 2026-06-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0031_deliveryrate_b2b_price_desk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Si défini, seul cet utilisateur peut utiliser le coupon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Points de fidélité (1 point = 1 DA)'),
        ),
    ]
