# Generated by Django 6.0.3 on 2026-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0032_coupon_user_userprofile_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mylerz_barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code-barres Mylerz'),
        ),
        migrations.AddField(
            model_name='order',
            name='mylerz_pickup_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code de collecte Mylerz'),
        ),
        migrations.AddField(
            model_name='order',
            name='mylerz_status',
            field=models.CharField(blank=True, max_length=200, verbose_name='Statut Mylerz'),
        ),
    ]
