# Generated by Django 6.0.3 on 2026-06-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0035_newsletterhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum pour bénéficier de la livraison gratuite (0 = désactivé)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='new_account_discount_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='new_account_discount_percent',
            field=models.DecimalField(decimal_places=2, default=10, help_text="Pourcentage de remise offert lors de la création d'un compte", max_digits=5),
        ),
    ]
