# Generated by Django 6.0.3 on 2026-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0036_sitesettings_free_shipping_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='multi_products', to='pioveapp.category'),
        ),
    ]
