# Generated by Django 6.0.3 on 2026-06-16 17:27

from django.db import migrations


def copy_categories(apps, schema_editor):
    Product = apps.get_model('pioveapp', 'Product')
    for product in Product.objects.all():
        if product.category:
            product.categories.add(product.category)

class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0037_product_categories'),
    ]

    operations = [
        migrations.RunPython(copy_categories),
    ]
