# Generated by Django 6.0.3 on 2026-06-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0038_auto_20260616_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
