# Generated by Django 6.0.3 on 2026-06-28 14:46

from django.db import migrations


def load_delivery_rates(apps, schema_editor):
    DeliveryCompany = apps.get_model('pioveapp', 'DeliveryCompany')
    DeliveryRate = apps.get_model('pioveapp', 'DeliveryRate')
    
    zones = {
        360: ['Alger'],
        450: ['Blida', 'Boumerdes', 'Tipaza'],
        630: ['Tizi Ouzou', 'Bouira', 'Medea', 'Ain Defla', 'Chlef'],
        720: ['Annaba', 'Jijel', 'Skikda', 'Bejaia', 'Mila', 'Oran', 'Tlemcen', 'Tiaret', 'Mascara', 'Sidi Bel Abbes', 'Ain Temouchent', 'Mostaganem', 'Relizane', 'Saida', 'Tissemsilt', 'Setif', 'Constantine', 'Bordj Bou Arreridj'],
        810: ['Souk Ahras', 'Guelma', 'El Tarf', 'Khenchela', 'Batna', 'Oum El Bouaghi', 'Tebessa', "M'sila", 'Laghouat', 'Ghardaia', 'Djelfa', 'Biskra'],
        1080: ['Ouargla', 'El Bayadh', 'El Oued', 'Touggourt', "El M'Ghair", 'El Meniaa', 'Ouled Djellal'],
        1440: ['Bechar', 'Tamanrasset', 'Adrar', 'Illizi', 'Tindouf', 'Naama', 'Bordj Badji Mokhtar', 'Timimoun', 'Djanet', 'In Salah', 'In Guezzam', 'Beni Abbes']
    }
    
    if not DeliveryCompany.objects.exists():
        DeliveryCompany.objects.create(name='Standard', is_active=True)

    companies = DeliveryCompany.objects.all()
    
    for company in companies:
        for price, wilayas in zones.items():
            for wilaya in wilayas:
                DeliveryRate.objects.update_or_create(
                    company=company,
                    wilaya_name=wilaya,
                    defaults={
                        'price_home': price,
                        'b2b_price_home': price,
                    }
                )

def reverse_delivery_rates(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0039_remove_product_category'),
    ]

    operations = [
        migrations.RunPython(load_delivery_rates, reverse_delivery_rates)
    ]
