# Generated by Django 6.0.3 on 2026-07-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0041_productimage_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contenance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contenance du produit (ex: 5.3)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='contenance_unit',
            field=models.CharField(blank=True, default='g', help_text='Unité de contenance (g, ml, oz...)', max_length=20),
        ),
    ]
