# Generated by Django 6.0.3 on 2026-07-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0042_product_contenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Disponibilité de cette variation'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix spécifique à cette variation (laissez vide pour utiliser le prix du produit)', max_digits=10, null=True),
        ),
    ]
