# Generated by Django 6.0.3 on 2026-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0043_productvariant_price_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Courte description affichée sous la contenance sur la page produit', max_length=300),
        ),
    ]
