# Generated by Django 6.0.3 on 2026-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0044_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, default='', help_text='ID du pixel Meta (Facebook) — ex: 2139405799887149', max_length=50),
        ),
    ]
