# Generated by Django 6.0.3 on 2026-07-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0047_add_order_source_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_pixel_id',
            field=models.CharField(blank=True, default='', help_text='ID du pixel TikTok — ex: C1234567890', max_length=50),
        ),
    ]
