# Generated by Django 6.0.3 on 2026-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0049_order_deleted_at_order_deleted_by_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='2ème numéro de téléphone'),
        ),
    ]
