# Generated by Django 6.0.3 on 2026-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0050_add_guest_phone2_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('en_cours', 'En cours'), ('confirmed', 'Confirme'), ('shipped', 'En livraison'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Annulee'), ('returned', 'Retournee')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('en_cours', 'En cours'), ('confirmed', 'Confirme'), ('shipped', 'En livraison'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Annulee'), ('returned', 'Retournee')], max_length=20),
        ),
    ]
