# Generated by Django 6.0.3 on 2026-07-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0051_add_en_cours_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='choice_group',
            field=models.CharField(blank=True, default='', help_text="Groupe de choix pour les produits collection (ex: 'Choix 01'). Laisser vide si pas de collection.", max_length=100),
        ),
    ]
