# Generated by Django 6.0.3 on 2026-08-02 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0055_banner_image_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boutique_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente de retrait'), ('ready', 'Prête à retirer'), ('collected', 'Récupérée'), ('cancelled', 'Annulée')], default='', max_length=20, verbose_name='Statut Boutique'),
        ),
        migrations.AddField(
            model_name='order',
            name='boutique_transferred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Transférée en boutique le'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('en_cours', 'En cours'), ('payment_failed', 'Paiement échoué'), ('confirmed', 'Confirme'), ('shipped', 'En livraison'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Annulee'), ('returned', 'Retournee'), ('boutique', 'En boutique')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('en_cours', 'En cours'), ('payment_failed', 'Paiement échoué'), ('confirmed', 'Confirme'), ('shipped', 'En livraison'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Annulee'), ('returned', 'Retournee'), ('boutique', 'En boutique')], max_length=20),
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('wilaya', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boutique_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pioveapp.boutique', verbose_name='Boutique'),
        ),
    ]
