# Generated by Django 6.0.3 on 2026-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0057_add_yassir_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
