# Generated by Django 6.0.3 on 2026-09-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0058_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code Produit (SKU)'),
        ),
    ]
