# Generated by Django 6.0.3 on 2026-08-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0058_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='show_image_in_swatch',
            field=models.BooleanField(default=True, help_text="Afficher l'image dans le cercle de variation (si disponible)"),
        ),
    ]
