# Generated by Django 6.0.3 on 2026-10-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0059_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_per_box',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité par boîte'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_per_carton',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité par carton'),
        ),
    ]
