# Generated by Django 6.0.3 on 2026-10-06 19:37

import pioveapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioveapp', '0060_product_qty_per_box_product_qty_per_carton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=pioveapp.models.safe_banner_upload),
        ),
    ]
